import mongoose, { Document, Schema } from "mongoose";

export type LogisticsProviderName =
  | "shiprocket"
  | "delhivery"
  | "bluedart"
  | "xpressbees"
  | "other";

export type ShippingStatus =
  | "pending"
  | "created"
  | "awb_assigned"
  | "pickup_scheduled"
  | "picked_up"
  | "in_transit"
  | "out_for_delivery"
  | "delivered"
  | "failed"
  | "cancelled"
  | "rto_initiated"
  | "rto_in_transit"
  | "rto_delivered";

export interface ITrackingEvent {
  status: ShippingStatus;
  statusCode?: string;

  activity?: string;
  location?: string;

  timestamp: Date;

  providerStatus?: string;
  providerStatusCode?: string;
}

export interface IShipping extends Document {
  sellerOrder: mongoose.Types.ObjectId;

  provider: LogisticsProviderName;

  // IDs generated by the logistics provider
  providerOrderId?: string;
  providerShipmentId?: string;

  // Courier information
  awb?: string;
  courierName?: string;
  courierCompanyId?: string;

  // Tracking
  trackingUrl?: string;

  // Our normalized status
  status: ShippingStatus;

  // Raw provider status
  providerStatus?: string;
  providerStatusCode?: string;

  // Expected delivery
  etd?: Date;

  // Pickup / shipment lifecycle
  pickupScheduledDate?: Date;
  pickedUpAt?: Date;
  dispatchedAt?: Date;
  deliveredAt?: Date;

  // Return / RTO
  isReturn: boolean;
  returnAwb?: string;

  // Documents
  labelUrl?: string;
  manifestUrl?: string;
  invoiceUrl?: string;

  // Sync information
  lastSyncedAt?: Date;

  trackingEvents: ITrackingEvent[];

  createdAt: Date;
  updatedAt: Date;
}

const trackingEventSchema = new Schema<ITrackingEvent>(
  {
    status: {
      type: String,
      required: true,
    },

    statusCode: {
      type: String,
    },

    activity: {
      type: String,
    },

    location: {
      type: String,
      trim: true,
    },

    timestamp: {
      type: Date,
      required: true,
    },

    providerStatus: {
      type: String,
    },

    providerStatusCode: {
      type: String,
    },
  },
  {
    _id: true,
  },
);

const shippingSchema = new Schema<IShipping>(
  {
    sellerOrder: {
      type: Schema.Types.ObjectId,
      ref: "SellerOrder",
      required: true,
      index: true,
    },

    provider: {
      type: String,
      enum: ["shiprocket", "delhivery", "bluedart", "xpressbees", "other"],
      required: true,
      index: true,
    },

    providerOrderId: {
      type: String,
      trim: true,
      index: true,
    },

    providerShipmentId: {
      type: String,
      trim: true,
      index: true,
    },

    awb: {
      type: String,
      trim: true,
      index: true,
    },

    courierName: {
      type: String,
      trim: true,
    },

    courierCompanyId: {
      type: String,
      trim: true,
    },

    trackingUrl: {
      type: String,
      trim: true,
    },

    status: {
      type: String,
      enum: [
        "pending",
        "created",
        "awb_assigned",
        "pickup_scheduled",
        "picked_up",
        "in_transit",
        "out_for_delivery",
        "delivered",
        "failed",
        "cancelled",
        "rto_initiated",
        "rto_in_transit",
        "rto_delivered",
      ],
      default: "pending",
      required: true,
      index: true,
    },

    providerStatus: {
      type: String,
      trim: true,
    },

    providerStatusCode: {
      type: String,
      trim: true,
    },

    etd: {
      type: Date,
    },

    pickupScheduledDate: {
      type: Date,
    },

    pickedUpAt: {
      type: Date,
    },

    dispatchedAt: {
      type: Date,
    },

    deliveredAt: {
      type: Date,
    },

    isReturn: {
      type: Boolean,
      default: false,
      index: true,
    },

    returnAwb: {
      type: String,
      trim: true,
      index: true,
    },

    labelUrl: {
      type: String,
      trim: true,
    },

    manifestUrl: {
      type: String,
      trim: true,
    },

    invoiceUrl: {
      type: String,
      trim: true,
    },

    lastSyncedAt: {
      type: Date,
    },

    trackingEvents: {
      type: [trackingEventSchema],
      default: [],
    },
  },
  {
    timestamps: true,
  },
);

/**
 * A seller order may have multiple shipping records.
 *
 * Example:
 * SellerOrder
 *   ├── Shiprocket shipment
 *   ├── Delhivery shipment
 *   └── Return shipment
 */
shippingSchema.index({
  sellerOrder: 1,
  provider: 1,
});

shippingSchema.index({
  provider: 1,
  providerShipmentId: 1,
});

shippingSchema.index({
  provider: 1,
  awb: 1,
});

export default mongoose.model<IShipping>("Shipping", shippingSchema);
