export const sarees = [
  // 1
  {
    _id: "1",
    groupId: "whiterose-embroidered-01",
    images: [
      "https://upload.meeshosupplyassets.com/cataloging/1785228322607/WhiteRose-Lavender-1.jpeg",
      "https://upload.meeshosupplyassets.com/cataloging/1785228322375/WhiteRose-Lavender-2.jpeg",
      "https://upload.meeshosupplyassets.com/cataloging/1785228322644/WhiteRose-Lavender-3.jpeg",
      "https://upload.meeshosupplyassets.com/cataloging/1785228322636/WhiteRose-Lavender-4.jpeg",
    ],
    title: "White Rose Lavender Embroidered Saree",
    brand: "WhiteRose",
    category: "Designer Sarees",
    fabric: "Georgette",
    color: "Lavender",
    pattern: "Embroidered",
    ornamentation: "Embroidered",
    border: "Embroidered",
    occasion: "Festive",
    sareeType: "Designer Saree",
    blouseType: "Embroidered Blouse",
    blouseColor: "Lavender",
    blouseIncluded: true,
    work: "Embroidery Work",
    condition: "New",
    price: 1899,
    discount: 10,
    finalPrice: 1709,
    shippingCharge: 49,
    description:
      "Elegant lavender saree featuring beautiful embroidery and a graceful designer finish. Perfect for festive occasions, parties and celebrations.",
    createdAt: new Date("2026-08-01"),
    seller: {
      name: "WhiteRose",
      contact: "9876543201",
    },
  },

  // 2
  {
    _id: "2",
    groupId: "whiterose-embroidered-01",
    images: [
      "https://upload.meeshosupplyassets.com/cataloging/1785228253132/WhiteRose-Mehendi-1.jpeg",
      "https://upload.meeshosupplyassets.com/cataloging/1785228253037/WhiteRose-Mehendi-2.jpeg",
      "https://upload.meeshosupplyassets.com/cataloging/1785228252931/WhiteRose-Mehendi-3.jpeg",
      "https://upload.meeshosupplyassets.com/cataloging/1785228253211/WhiteRose-Mehendi-4.jpeg",
    ],
    title: "White Rose Mehendi Green Designer Saree",
    brand: "WhiteRose",
    category: "Designer Sarees",
    fabric: "Georgette",
    color: "Green",
    pattern: "Embroidered",
    ornamentation: "Embroidered",
    border: "Embroidered",
    occasion: "Festive",
    sareeType: "Designer Saree",
    blouseType: "Embroidered Blouse",
    blouseColor: "Green",
    blouseIncluded: true,
    work: "Embroidery Work",
    condition: "New",
    price: 1999,
    discount: 10,
    finalPrice: 1799,
    shippingCharge: 49,
    description:
      "Stylish mehendi green designer saree with elegant embroidery and a sophisticated festive look.",
    createdAt: new Date("2026-08-02"),
    seller: {
      name: "WhiteRose",
      contact: "9876543201",
    },
  },

  // 3
  {
    _id: "3",
    groupId: "whiterose-embroidered-01",
    images: [
      "https://upload.meeshosupplyassets.com/cataloging/1783664150175/DUCK_YELLOW_T_02-1.jpg",
      "https://upload.meeshosupplyassets.com/cataloging/1783664150044/DUCK_YELLOW_T_02-2.jpg",
      "https://upload.meeshosupplyassets.com/cataloging/1783664152702/DUCK_YELLOW_T_02-3.jpg",
      "https://upload.meeshosupplyassets.com/cataloging/1783664153248/DUCK_YELLOW_T_02-4.jpg",
    ],
    title: "Duck Yellow Embroidered Saree",
    brand: "Duck",
    category: "Party Wear Sarees",
    fabric: "Georgette",
    color: "Yellow",
    pattern: "Embroidered",
    ornamentation: "Embroidered",
    border: "Embroidered",
    occasion: "Party",
    sareeType: "Fancy Saree",
    blouseType: "Embroidered Blouse",
    blouseColor: "Yellow",
    blouseIncluded: true,
    work: "Embroidery Work",
    condition: "New",
    price: 1799,
    discount: 10,
    finalPrice: 1619,
    shippingCharge: 49,
    description:
      "Bright yellow designer saree with elegant embroidery, perfect for parties, festive gatherings and celebrations.",
    createdAt: new Date("2026-08-03"),
    seller: {
      name: "Duck",
      contact: "9876543202",
    },
  },

  // 4
  {
    _id: "4",
    groupId: "whiterose-embroidered-01",
    images: [
      "https://upload.meeshosupplyassets.com/cataloging/1783664080776/DUCK_SKYBLUE_T_02-2.jpg",
      "https://upload.meeshosupplyassets.com/cataloging/1783664080875/DUCK_SKYBLUE_T_02-1.jpg",
      "https://upload.meeshosupplyassets.com/cataloging/1783664079860/DUCK_SKYBLUE_T_02-3.jpg",
      "https://upload.meeshosupplyassets.com/cataloging/1783664079919/DUCK_SKYBLUE_T_02-4.jpg",
    ],
    title: "Duck Sky Blue Designer Saree",
    brand: "Duck",
    category: "Designer Sarees",
    fabric: "Georgette",
    color: "Blue",
    pattern: "Embroidered",
    ornamentation: "Embroidered",
    border: "Embroidered",
    occasion: "Party",
    sareeType: "Designer Saree",
    blouseType: "Embroidered Blouse",
    blouseColor: "Blue",
    blouseIncluded: true,
    work: "Embroidery Work",
    condition: "New",
    price: 1899,
    discount: 10,
    finalPrice: 1709,
    shippingCharge: 49,
    description:
      "Elegant sky blue designer saree with intricate embroidery and a graceful contemporary look.",
    createdAt: new Date("2026-08-04"),
    seller: {
      name: "Duck",
      contact: "9876543202",
    },
  },

  // 5
  {
    _id: "5",
    groupId: "",
    images: [
      "https://upload.meeshosupplyassets.com/cataloging/1783664020329/DUCK_PISTA_T_02-2.jpg",
      "https://upload.meeshosupplyassets.com/cataloging/1783664019927/DUCK_PISTA_T_02-1.jpg",
      "https://upload.meeshosupplyassets.com/cataloging/1783664024187/DUCK_PISTA_T_02-3.jpg",
      "https://upload.meeshosupplyassets.com/cataloging/1783664023387/DUCK_PISTA_T_02-4.jpg",
    ],
    title: "Duck Pista Green Embroidered Saree",
    brand: "Duck",
    category: "Festive Sarees",
    fabric: "Georgette",
    color: "Sea Green",
    pattern: "Embroidered",
    ornamentation: "Embroidered",
    border: "Embroidered",
    occasion: "Festive",
    sareeType: "Designer Saree",
    blouseType: "Embroidered Blouse",
    blouseColor: "Sea Green",
    blouseIncluded: true,
    work: "Embroidery Work",
    condition: "New",
    price: 1899,
    discount: 10,
    finalPrice: 1709,
    shippingCharge: 49,
    description:
      "Beautiful pista green saree with delicate embroidery and an elegant festive appearance.",
    createdAt: new Date("2026-08-05"),
    seller: {
      name: "Duck",
      contact: "9876543202",
    },
  },

  // 6
  {
    _id: "6",
    groupId: "whiterose-embroidered-01",
    images: [
      "https://upload.meeshosupplyassets.com/cataloging/1783663946856/DUCK_PINK_T_02-2.jpg",
      "https://upload.meeshosupplyassets.com/cataloging/1783663947161/DUCK_PINK_T_02-1.jpg",
      "https://upload.meeshosupplyassets.com/cataloging/1783663946841/DUCK_PINK_T_02-3.jpg",
      "https://upload.meeshosupplyassets.com/cataloging/1783663947168/DUCK_PINK_T_02-4.jpg",
    ],
    title: "Duck Pink Embroidered Saree",
    brand: "Duck",
    category: "Party Wear Sarees",
    fabric: "Georgette",
    color: "Pink",
    pattern: "Embroidered",
    ornamentation: "Embroidered",
    border: "Embroidered",
    occasion: "Party",
    sareeType: "Fancy Saree",
    blouseType: "Embroidered Blouse",
    blouseColor: "Pink",
    blouseIncluded: true,
    work: "Embroidery Work",
    condition: "New",
    price: 1799,
    discount: 10,
    finalPrice: 1619,
    shippingCharge: 49,
    description:
      "Charming pink saree with beautiful embroidery, ideal for parties and special occasions.",
    createdAt: new Date("2026-08-06"),
    seller: {
      name: "Duck",
      contact: "9876543202",
    },
  },

  // 7
  {
    _id: "7",
    groupId: "whiterose-embroidered-01",
    images: [
      "https://upload.meeshosupplyassets.com/cataloging/1783663890771/DUCK_PEACH_T_02-2.jpg",
      "https://upload.meeshosupplyassets.com/cataloging/1783663890771/DUCK_PEACH_T_02-2.jpg",
      "https://upload.meeshosupplyassets.com/cataloging/1783663890699/DUCK_PEACH_T_02-3.jpg",
      "https://upload.meeshosupplyassets.com/cataloging/1783663887357/DUCK_PEACH_T_02-4.jpg",
    ],
    title: "Duck Peach Designer Saree",
    brand: "Duck",
    category: "Designer Sarees",
    fabric: "Georgette",
    color: "Peach",
    pattern: "Embroidered",
    ornamentation: "Embroidered",
    border: "Embroidered",
    occasion: "Festive",
    sareeType: "Designer Saree",
    blouseType: "Embroidered Blouse",
    blouseColor: "Peach",
    blouseIncluded: true,
    work: "Embroidery Work",
    condition: "New",
    price: 1899,
    discount: 10,
    finalPrice: 1709,
    shippingCharge: 49,
    description:
      "Soft peach designer saree featuring elegant embroidery and a beautiful feminine finish.",
    createdAt: new Date("2026-08-07"),
    seller: {
      name: "Duck",
      contact: "9876543202",
    },
  },

  // 8
  {
    _id: "8",
    groupId: "",
    images: [
      "https://upload.meeshosupplyassets.com/cataloging/1783663755237/DUCK_LAVENDER_T_02-2.jpg",
      "https://upload.meeshosupplyassets.com/cataloging/1783663752916/DUCK_LAVENDER_T_02-1.jpg",
      "https://upload.meeshosupplyassets.com/cataloging/1783663752803/DUCK_LAVENDER_T_02-3.jpg",
      "https://upload.meeshosupplyassets.com/cataloging/1783663755180/DUCK_LAVENDER_T_02-4.jpg",
    ],
    title: "Duck Lavender Embroidered Saree",
    brand: "Duck",
    category: "Designer Sarees",
    fabric: "Georgette",
    color: "Lavender",
    pattern: "Embroidered",
    ornamentation: "Embroidered",
    border: "Embroidered",
    occasion: "Party",
    sareeType: "Designer Saree",
    blouseType: "Embroidered Blouse",
    blouseColor: "Lavender",
    blouseIncluded: true,
    work: "Embroidery Work",
    condition: "New",
    price: 1999,
    discount: 10,
    finalPrice: 1799,
    shippingCharge: 49,
    description:
      "Elegant lavender saree with intricate embroidery and a stylish designer finish.",
    createdAt: new Date("2026-08-08"),
    seller: {
      name: "Duck",
      contact: "9876543202",
    },
  },

  // 9
  {
    _id: "9",
    groupId: "",
    images: [
      "https://upload.meeshosupplyassets.com/cataloging/1783663630297/DUCK-MUSTARD-T-01-3.jpg",
      "https://upload.meeshosupplyassets.com/cataloging/1783663630297/DUCK-MUSTARD-T-01-3.jpg",
      "https://upload.meeshosupplyassets.com/cataloging/1783663629636/DUCK-MUSTARD-T-01-2.jpg",
      "https://upload.meeshosupplyassets.com/cataloging/1783663629555/DUCK-MUSTARD-T-01-4.jpg",
    ],
    title: "Duck Mustard Yellow Saree",
    brand: "Duck",
    category: "Festive Sarees",
    fabric: "Georgette",
    color: "Mustard",
    pattern: "Embroidered",
    ornamentation: "Embroidered",
    border: "Embroidered",
    occasion: "Festive",
    sareeType: "Designer Saree",
    blouseType: "Embroidered Blouse",
    blouseColor: "Mustard",
    blouseIncluded: true,
    work: "Embroidery Work",
    condition: "New",
    price: 1899,
    discount: 10,
    finalPrice: 1709,
    shippingCharge: 49,
    description:
      "Mustard yellow designer saree with elegant embroidery, perfect for festive celebrations.",
    createdAt: new Date("2026-08-09"),
    seller: {
      name: "Duck",
      contact: "9876543202",
    },
  },

  // 10
  {
    _id: "10",
    groupId: "",
    images: [
      "https://upload.meeshosupplyassets.com/cataloging/1783663504154/DUCK_PISTA_T_01-1.jpg",
      "https://upload.meeshosupplyassets.com/cataloging/1783663504610/DUCK_PISTA_T_01-2.jpg",
      "https://upload.meeshosupplyassets.com/cataloging/1783663501274/DUCK_PISTA_T_01-3.jpg",
      "https://upload.meeshosupplyassets.com/cataloging/1783663501166/DUCK_PISTA_T_01-4.jpg",
    ],
    title: "Duck Pista Green Saree",
    brand: "Duck",
    category: "Festive Sarees",
    fabric: "Georgette",
    color: "Sea Green",
    pattern: "Embroidered",
    ornamentation: "Embroidered",
    border: "Embroidered",
    occasion: "Festive",
    sareeType: "Designer Saree",
    blouseType: "Embroidered Blouse",
    blouseColor: "Sea Green",
    blouseIncluded: true,
    work: "Embroidery Work",
    condition: "New",
    price: 1799,
    discount: 10,
    finalPrice: 1619,
    shippingCharge: 49,
    description:
      "Fresh pista green saree with delicate embroidery and a graceful festive design.",
    createdAt: new Date("2026-08-10"),
    seller: {
      name: "Duck",
      contact: "9876543202",
    },
  },

  // 11
  {
    _id: "11",
    groupId: "",
    images: [
      "https://upload.meeshosupplyassets.com/cataloging/1783663375440/DUCK_PINK_T_01-2.jpg",
      "https://upload.meeshosupplyassets.com/cataloging/1783663375175/DUCK_PINK_T_01-1.jpg",
      "https://upload.meeshosupplyassets.com/cataloging/1783663377534/DUCK_PINK_T_01-3.jpg",
      "https://upload.meeshosupplyassets.com/cataloging/1783663377482/DUCK_PINK_T_01-4.jpg",
    ],
    title: "Duck Pink Designer Saree",
    brand: "Duck",
    category: "Party Wear Sarees",
    fabric: "Georgette",
    color: "Pink",
    pattern: "Embroidered",
    ornamentation: "Embroidered",
    border: "Embroidered",
    occasion: "Party",
    sareeType: "Fancy Saree",
    blouseType: "Embroidered Blouse",
    blouseColor: "Pink",
    blouseIncluded: true,
    work: "Embroidery Work",
    condition: "New",
    price: 1899,
    discount: 10,
    finalPrice: 1709,
    shippingCharge: 49,
    description:
      "Pretty pink designer saree with detailed embroidery for a stylish party look.",
    createdAt: new Date("2026-08-11"),
    seller: {
      name: "Duck",
      contact: "9876543202",
    },
  },

  // 12
  {
    _id: "12",
    images: [
      "https://upload.meeshosupplyassets.com/cataloging/1783663073317/DUCK_PEACH_T_01-2.jpg",
      "https://upload.meeshosupplyassets.com/cataloging/1783663068866/DUCK_PEACH_T_01-1.jpg",
      "https://upload.meeshosupplyassets.com/cataloging/1783663067660/DUCK_PEACH_T_01-3.jpg",
      "https://upload.meeshosupplyassets.com/cataloging/1783663073212/DUCK_PEACH_T_01-4.jpg",
    ],
    title: "Duck Peach Embroidered Saree",
    brand: "Duck",
    category: "Designer Sarees",
    fabric: "Georgette",
    color: "Peach",
    pattern: "Embroidered",
    ornamentation: "Embroidered",
    border: "Embroidered",
    occasion: "Festive",
    sareeType: "Designer Saree",
    blouseType: "Embroidered Blouse",
    blouseColor: "Peach",
    blouseIncluded: true,
    work: "Embroidery Work",
    condition: "New",
    price: 1899,
    discount: 10,
    finalPrice: 1709,
    shippingCharge: 49,
    description:
      "Elegant peach georgette saree with beautiful embroidery and a sophisticated designer appearance.",
    createdAt: new Date("2026-08-12"),
    seller: {
      name: "Duck",
      contact: "9876543202",
    },
  },

  // 13
  {
    _id: "13",
    images: [
      "https://upload.meeshosupplyassets.com/cataloging/1783608342596/DUCK_BLUE_T_01-2.jpg",
      "https://upload.meeshosupplyassets.com/cataloging/1783608342596/DUCK_BLUE_T_01-2.jpg",
      "https://upload.meeshosupplyassets.com/cataloging/1783608342851/DUCK_BLUE_T_01-3.jpg",
      "https://upload.meeshosupplyassets.com/cataloging/1783608338688/DUCK_BLUE_T_01-4.jpg",
    ],
    title: "Duck Blue Embroidered Saree",
    brand: "Duck",
    category: "Party Wear Sarees",
    fabric: "Georgette",
    color: "Blue",
    pattern: "Embroidered",
    ornamentation: "Embroidered",
    border: "Embroidered",
    occasion: "Party",
    sareeType: "Designer Saree",
    blouseType: "Embroidered Blouse",
    blouseColor: "Blue",
    blouseIncluded: true,
    work: "Embroidery Work",
    condition: "New",
    price: 1999,
    discount: 10,
    finalPrice: 1799,
    shippingCharge: 49,
    description:
      "Rich blue saree with elegant embroidery, designed for parties and special occasions.",
    createdAt: new Date("2026-08-13"),
    seller: {
      name: "Duck",
      contact: "9876543202",
    },
  },

  // 14
  {
    _id: "14",
    images: [
      "https://upload.meeshosupplyassets.com/cataloging/1783608609695/DUCK_LAVENDER_T_01-1.jpg",
      "https://upload.meeshosupplyassets.com/cataloging/1783608558265/DUCK_LAVENDER_T_01-2.jpg",
      "https://upload.meeshosupplyassets.com/cataloging/1783608612006/DUCK_LAVENDER_T_01-3.jpg",
      "https://upload.meeshosupplyassets.com/cataloging/1783608558013/DUCK_LAVENDER_T_01-4.jpg",
    ],
    title: "Duck Lavender Designer Saree",
    brand: "Duck",
    category: "Designer Sarees",
    fabric: "Georgette",
    color: "Lavender",
    pattern: "Embroidered",
    ornamentation: "Embroidered",
    border: "Embroidered",
    occasion: "Party",
    sareeType: "Designer Saree",
    blouseType: "Embroidered Blouse",
    blouseColor: "Lavender",
    blouseIncluded: true,
    work: "Embroidery Work",
    condition: "New",
    price: 1999,
    discount: 10,
    finalPrice: 1799,
    shippingCharge: 49,
    description:
      "Beautiful lavender saree with delicate embroidery and a stylish designer finish.",
    createdAt: new Date("2026-08-14"),
    seller: {
      name: "Duck",
      contact: "9876543202",
    },
  },

  // 15
  {
    _id: "15",
    images: [
      "https://upload.meeshosupplyassets.com/cataloging/1783603768113/DUCK-PURPLE-M-01-1.jpg",
      "https://upload.meeshosupplyassets.com/cataloging/1783603768167/DUCK-PURPLE-M-01-3.jpg",
      "https://upload.meeshosupplyassets.com/cataloging/1783603768161/DUCK-PURPLE-M-01-2.jpg",
      "https://upload.meeshosupplyassets.com/cataloging/1783603768173/DUCK-PURPLE-M-01-4.jpg",
    ],
    title: "Duck Purple Embroidered Saree",
    brand: "Duck",
    category: "Party Wear Sarees",
    fabric: "Georgette",
    color: "Purple",
    pattern: "Embroidered",
    ornamentation: "Embroidered",
    border: "Embroidered",
    occasion: "Party",
    sareeType: "Fancy Saree",
    blouseType: "Embroidered Blouse",
    blouseColor: "Purple",
    blouseIncluded: true,
    work: "Embroidery Work",
    condition: "New",
    price: 1999,
    discount: 10,
    finalPrice: 1799,
    shippingCharge: 49,
    description:
      "Glamorous purple saree featuring elegant embroidery and a fashionable party-ready appearance.",
    createdAt: new Date("2026-08-15"),
    seller: {
      name: "Duck",
      contact: "9876543202",
    },
  },

  // 16
  {
    _id: "16",
    images: [
      "https://upload.meeshosupplyassets.com/cataloging/1783603389706/DUCK-Pink-M-01-3.jpeg",
      "https://upload.meeshosupplyassets.com/cataloging/1783603389755/DUCK-Pink-M-01-2.jpeg",
      "https://upload.meeshosupplyassets.com/cataloging/1783603389673/DUCK-Pink-M-01-4.jpeg",
      "https://upload.meeshosupplyassets.com/cataloging/1783603389707/DUCK-Pink-M-01-1.jpeg",
    ],
    title: "Duck Pink Fancy Saree",
    brand: "Duck",
    category: "Fancy Sarees",
    fabric: "Georgette",
    color: "Pink",
    pattern: "Embroidered",
    ornamentation: "Embroidered",
    border: "Embroidered",
    occasion: "Party",
    sareeType: "Fancy Saree",
    blouseType: "Embroidered Blouse",
    blouseColor: "Pink",
    blouseIncluded: true,
    work: "Embroidery Work",
    condition: "New",
    price: 1899,
    discount: 10,
    finalPrice: 1709,
    shippingCharge: 49,
    description:
      "Stylish pink fancy saree with attractive embroidery, perfect for parties and celebrations.",
    createdAt: new Date("2026-08-16"),
    seller: {
      name: "Duck",
      contact: "9876543202",
    },
  },

  // 17
  {
    _id: "17",
    images: [
      "https://upload.meeshosupplyassets.com/cataloging/1783603252600/DUCK-Blue-M-01-3.jpeg",
      "https://upload.meeshosupplyassets.com/cataloging/1783603252581/DUCK-Blue-M-01-4.jpeg",
      "https://upload.meeshosupplyassets.com/cataloging/1783603252641/DUCK-Blue-M-01-2.jpeg",
      "https://upload.meeshosupplyassets.com/cataloging/1783603252573/DUCK-Blue-M-01-1.jpeg",
    ],
    title: "Duck Blue Fancy Embroidered Saree",
    brand: "Duck",
    category: "Fancy Sarees",
    fabric: "Georgette",
    color: "Blue",
    pattern: "Embroidered",
    ornamentation: "Embroidered",
    border: "Embroidered",
    occasion: "Party",
    sareeType: "Fancy Saree",
    blouseType: "Embroidered Blouse",
    blouseColor: "Blue",
    blouseIncluded: true,
    work: "Embroidery Work",
    condition: "New",
    price: 1999,
    discount: 10,
    finalPrice: 1799,
    shippingCharge: 49,
    description:
      "Elegant blue fancy saree with detailed embroidery for a glamorous party look.",
    createdAt: new Date("2026-08-17"),
    seller: {
      name: "Duck",
      contact: "9876543202",
    },
  },

  // 18
  {
    _id: "18",
    images: [
      "https://upload.meeshosupplyassets.com/cataloging/1783602734802/DUCK-PistaGreen-M-01-1.jpeg",
      "https://upload.meeshosupplyassets.com/cataloging/1783602734818/DUCK-PistaGreen-M-01-4.jpeg",
      "https://upload.meeshosupplyassets.com/cataloging/1783602734767/DUCK-PistaGreen-M-01-3.jpeg",
      "https://upload.meeshosupplyassets.com/cataloging/1783602734797/DUCK-PistaGreen-M-01-2.jpeg",
    ],
    title: "Duck Pista Green Fancy Saree",
    brand: "Duck",
    category: "Festive Sarees",
    fabric: "Georgette",
    color: "Sea Green",
    pattern: "Embroidered",
    ornamentation: "Embroidered",
    border: "Embroidered",
    occasion: "Festive",
    sareeType: "Fancy Saree",
    blouseType: "Embroidered Blouse",
    blouseColor: "Sea Green",
    blouseIncluded: true,
    work: "Embroidery Work",
    condition: "New",
    price: 1899,
    discount: 10,
    finalPrice: 1709,
    shippingCharge: 49,
    description:
      "Fresh pista green fancy saree with beautiful embroidery, ideal for festive celebrations.",
    createdAt: new Date("2026-08-18"),
    seller: {
      name: "Duck",
      contact: "9876543202",
    },
  },

  // 19
  {
    _id: "19",
    images: [
      "https://upload.meeshosupplyassets.com/cataloging/1783602571296/DUCK-Maroon-M-01-2.jpeg",
      "https://upload.meeshosupplyassets.com/cataloging/1783602571295/DUCK-Maroon-M-01-3.jpeg",
      "https://upload.meeshosupplyassets.com/cataloging/1783602571301/DUCK-Maroon-M-01-1.jpeg",
      "https://upload.meeshosupplyassets.com/cataloging/1783602571310/DUCK-Maroon-M-01-4.jpeg",
    ],
    title: "Duck Maroon Embroidered Saree",
    brand: "Duck",
    category: "Party Wear Sarees",
    fabric: "Georgette",
    color: "Maroon",
    pattern: "Embroidered",
    ornamentation: "Embroidered",
    border: "Embroidered",
    occasion: "Party",
    sareeType: "Designer Saree",
    blouseType: "Embroidered Blouse",
    blouseColor: "Maroon",
    blouseIncluded: true,
    work: "Embroidery Work",
    condition: "New",
    price: 2099,
    discount: 10,
    finalPrice: 1889,
    shippingCharge: 49,
    description:
      "Rich maroon designer saree with intricate embroidery and an elegant party-ready appearance.",
    createdAt: new Date("2026-08-19"),
    seller: {
      name: "Duck",
      contact: "9876543202",
    },
  },

  // 20
  {
    _id: "20",
    images: [
      "https://upload.meeshosupplyassets.com/cataloging/1783602498020/DUCK-Yellow-M-01-3.jpeg",
      "https://upload.meeshosupplyassets.com/cataloging/1783602498046/DUCK-Yellow-M-01-2.jpeg",
      "https://upload.meeshosupplyassets.com/cataloging/1783602498027/DUCK-Yellow-M-01-1.jpeg",
      "https://upload.meeshosupplyassets.com/cataloging/1783602497979/DUCK-Yellow-M-01-4.jpeg",
    ],
    title: "Duck Yellow Fancy Saree",
    brand: "Duck",
    category: "Festive Sarees",
    fabric: "Georgette",
    color: "Yellow",
    pattern: "Embroidered",
    ornamentation: "Embroidered",
    border: "Embroidered",
    occasion: "Festive",
    sareeType: "Fancy Saree",
    blouseType: "Embroidered Blouse",
    blouseColor: "Yellow",
    blouseIncluded: true,
    work: "Embroidery Work",
    condition: "New",
    price: 1899,
    discount: 10,
    finalPrice: 1709,
    shippingCharge: 49,
    description:
      "Vibrant yellow fancy saree with elegant embroidery, perfect for festive occasions and celebrations.",
    createdAt: new Date("2026-08-20"),
    seller: {
      name: "Duck",
      contact: "9876543202",
    },
  },

  // 21
  {
    _id: "21",
    images: [
      "https://upload.meeshosupplyassets.com/cataloging/1783225097862/Rashmika-Red-3.jpeg",
      "https://upload.meeshosupplyassets.com/cataloging/1783225097790/Rashmika-Red-4.jpeg",
      "https://upload.meeshosupplyassets.com/cataloging/1783225097911/Rashmika-Red-2.jpeg",
      "https://upload.meeshosupplyassets.com/cataloging/1783225097870/Rashmika-Red-1.jpeg",
    ],
    title: "Rashmika Red Designer Saree",
    brand: "Rashmika",
    category: "Wedding Sarees",
    fabric: "Georgette",
    color: "Red",
    pattern: "Embroidered",
    ornamentation: "Embroidered",
    border: "Embroidered",
    occasion: "Wedding",
    sareeType: "Designer Saree",
    blouseType: "Embroidered Blouse",
    blouseColor: "Red",
    blouseIncluded: true,
    work: "Embroidery Work",
    condition: "New",
    price: 2299,
    discount: 10,
    finalPrice: 2069,
    shippingCharge: 59,
    description:
      "Beautiful red designer saree with elegant embroidery, perfect for weddings and grand celebrations.",
    createdAt: new Date("2026-08-21"),
    seller: {
      name: "Rashmika",
      contact: "9876543203",
    },
  },

  // 22
  {
    _id: "22",
    images: [
      "https://upload.meeshosupplyassets.com/cataloging/1783225041396/Rashmika-Purple-3.jpeg",
      "https://upload.meeshosupplyassets.com/cataloging/1783225041401/Rashmika-Purple-4.jpeg",
      "https://upload.meeshosupplyassets.com/cataloging/1783225041485/Rashmika-Purple-1.jpeg",
      "https://upload.meeshosupplyassets.com/cataloging/1783225041398/Rashmika-Purple-2.jpeg",
    ],
    title: "Rashmika Purple Embroidered Saree",
    brand: "Rashmika",
    category: "Party Wear Sarees",
    fabric: "Georgette",
    color: "Purple",
    pattern: "Embroidered",
    ornamentation: "Embroidered",
    border: "Embroidered",
    occasion: "Party",
    sareeType: "Designer Saree",
    blouseType: "Embroidered Blouse",
    blouseColor: "Purple",
    blouseIncluded: true,
    work: "Embroidery Work",
    condition: "New",
    price: 2199,
    discount: 10,
    finalPrice: 1979,
    shippingCharge: 49,
    description:
      "Gorgeous purple saree with intricate embroidery and an elegant designer look for parties and celebrations.",
    createdAt: new Date("2026-08-22"),
    seller: {
      name: "Rashmika",
      contact: "9876543203",
    },
  },

  // 23
  {
    _id: "23",
    images: [
      "https://upload.meeshosupplyassets.com/cataloging/1783224975859/Rashmika-Maroon-2.jpeg",
      "https://upload.meeshosupplyassets.com/cataloging/1783224975796/Rashmika-Maroon-4.jpeg",
      "https://upload.meeshosupplyassets.com/cataloging/1783224975842/Rashmika-Maroon-3.jpeg",
      "https://upload.meeshosupplyassets.com/cataloging/1783224975888/Rashmika-Maroon-1.jpeg",
    ],
    title: "Rashmika Maroon Designer Saree",
    brand: "Rashmika",
    category: "Wedding Sarees",
    fabric: "Georgette",
    color: "Maroon",
    pattern: "Embroidered",
    ornamentation: "Embroidered",
    border: "Embroidered",
    occasion: "Wedding",
    sareeType: "Designer Saree",
    blouseType: "Embroidered Blouse",
    blouseColor: "Maroon",
    blouseIncluded: true,
    work: "Embroidery Work",
    condition: "New",
    price: 2399,
    discount: 10,
    finalPrice: 2159,
    shippingCharge: 59,
    description:
      "Rich maroon designer saree with beautiful embroidery, ideal for weddings, receptions and festive celebrations.",
    createdAt: new Date("2026-08-23"),
    seller: {
      name: "Rashmika",
      contact: "9876543203",
    },
  },

  // 24
  {
    _id: "24",
    images: [
      "https://upload.meeshosupplyassets.com/cataloging/1783224894523/Rashmika-Green-3.jpeg",
      "https://upload.meeshosupplyassets.com/cataloging/1783224894370/Rashmika-Green-1.jpeg",
      "https://upload.meeshosupplyassets.com/cataloging/1783224894541/Rashmika-Green-2.jpeg",
      "https://upload.meeshosupplyassets.com/cataloging/1783224894483/Rashmika-Green-4.jpeg",
    ],
    title: "Rashmika Green Embroidered Saree",
    brand: "Rashmika",
    category: "Festive Sarees",
    fabric: "Georgette",
    color: "Green",
    pattern: "Embroidered",
    ornamentation: "Embroidered",
    border: "Embroidered",
    occasion: "Festive",
    sareeType: "Designer Saree",
    blouseType: "Embroidered Blouse",
    blouseColor: "Green",
    blouseIncluded: true,
    work: "Embroidery Work",
    condition: "New",
    price: 2199,
    discount: 10,
    finalPrice: 1979,
    shippingCharge: 49,
    description:
      "Elegant green designer saree featuring beautiful embroidery, perfect for festive occasions and celebrations.",
    createdAt: new Date("2026-08-24"),
    seller: {
      name: "Rashmika",
      contact: "9876543203",
    },
  },
];

export const filters = {
  
  brand: [
    "WhiteRose",
    "Duck",
    "Rashmika",
  ],
  category: [
    "Party Wear Sarees",
    "Designer Sarees",
    "Wedding Sarees",
    "Festive Sarees",
    "Fancy Sarees",
    "Traditional Sarees",
  ],


  color: [
    "Red",
    "Blue",
    "Green",
    "Black",
    "Purple",
    "White",
    "Pink",
    "Grey",
    "Brown",
    "Yellow",
    "Orange",
    "Navy Blue",
    "Maroon",
    "Cream",
    "Silver",
    "Gold",
    "Beige",
    "Peach",
    "Burgundy",
    "Teal",
    "Lavender",
    "Magenta",
    "Mauve",
    "Coral",
    "Fuchsia",
  ],
  //   fabric: [
  //   "Georgette",
  //   "Silk",
  //   "Organza",
  //   "Chiffon",
  //   "Cotton",
  //   "Chanderi",
  //   "Crepe",
  //   "Net",
  // ],


  // pattern: [
  //   "Embroidered",
  //   "Embellished",
  //   "Printed",
  //   "Solid",
  //   "Woven Design",
  //   "Striped",
  //   "Checked",
  // ],

  // occasion: [
  //   "Casual",
  //   "Festive",
  //   "Party",
  //   "Wedding",
  //   "Formal",
  // ],

};
